  <!-- ========= SCRIPT PRINCIPAL ========= -->
  <script>
  /* ====== PACIENTES (tu backend GAS) ====== */
  const API_URL = 'https://script.google.com/macros/s/AKfycbxxL7Sau_wC4Vg5-DLzK0y41EjlR6S1hgWEywnLIbUCSKlAoKJQY5doeAchSElQWulpcg/exec';
  const $ = s => document.querySelector(s);
  const show = (el,flag)=> el.classList.toggle('hidden', !flag);
  const netState = $('#netState'); const showNet = m => netState.textContent = m || '';
  if(!HTMLDialogElement.prototype.showModal){ for(const d of document.querySelectorAll('dialog')){ d.showModal = ()=> d.setAttribute('open',''); d.close = ()=> d.removeAttribute('open'); } }
  async function apiGet(params){ const url=new URL(API_URL); Object.entries(params||{}).forEach(([k,v])=> url.searchParams.set(k,v)); const res=await fetch(url.toString()); const txt=await res.text(); try{return JSON.parse(txt);}catch{return [];} }
  async function apiPost(body){ const res=await fetch(API_URL,{method:'POST',body:JSON.stringify(body)}); const txt=await res.text(); try{return JSON.parse(txt);}catch{return {ok:true,raw:txt}} }
  let PSTATE={patients:[],query:''};
  function humanDate(d){ return d? new Date(d).toISOString().slice(0,10) : '—'; }
  function renderPatients(){ const listEl=$('#list'), detailEl=$('#detail'); detailEl.classList.add('hidden'); listEl.innerHTML=''; const q=(PSTATE.query||'').toLowerCase(); const rows=PSTATE.patients.filter(p=>(`${p.nombre||''} ${p.documento||''} ${p.telefono||''}`).toLowerCase().includes(q)); if(!rows.length){ listEl.innerHTML='<div class="text-gray-500">No hay pacientes.</div>'; return;} for(const p of rows){ const div=document.createElement('div'); div.className='bg-white rounded-2xl shadow p-4 flex items-center justify-between'; div.innerHTML=`<div><button class="text-lg font-semibold hover:underline" data-open="${p.id}">${p.nombre}</button><div class="text-sm text-gray-500">Doc: ${p.documento||'—'} · Tel: ${p.telefono||'—'} · Reg: ${humanDate(p.fecha_creacion)}</div></div><div class="flex items-center gap-2"><button class="px-3 py-2 rounded-xl bg-amber-500 text-white hover:bg-amber-600" data-edit="${p.id}">Editar</button><button class="px-3 py-2 rounded-xl bg-red-600 text-white hover:bg-red-700" data-del="${p.id}">Eliminar</button></div>`; listEl.appendChild(div);} listEl.querySelectorAll('[data-open]').forEach(b=> b.onclick=()=> openPatientDetail(b.dataset.open)); listEl.querySelectorAll('[data-edit]').forEach(b=> b.onclick=()=> openPatientForm(b.dataset.edit)); listEl.querySelectorAll('[data-del]').forEach(b=> b.onclick=()=> deletePatient(b.dataset.del)); }
  async function loadPatients(){ try{ showNet('Cargando...'); const data=await apiGet({mode:'patients'}); PSTATE.patients=Array.isArray(data)?data:[]; renderPatients(); showNet(''); }catch(e){ $('#list').innerHTML=`<div class='text-red-700 bg-red-50 border border-red-200 rounded-xl p-3'>No se pudo cargar desde Google Sheets.<br><small>${e.message}</small></div>`; showNet('Error'); } }
  function openPatientForm(id){ const dlg=$('#patientDialog'); $('#patientForm').reset(); $('#dialogTitle').textContent=id?'Editar paciente':'Nuevo paciente'; $('#p_id').value=id||''; if(id){ const p=PSTATE.patients.find(x=> x.id===id); if(p){ $('#p_full_name').value=p.nombre||''; $('#p_document_id').value=p.documento||''; $('#p_phone').value=p.telefono||''; $('#p_email').value=p.email||''; $('#p_birthdate').value=p.fecha_nacimiento||''; $('#p_address').value=p.direccion||''; $('#p_notes').value=p.notas||''; } } dlg.showModal(); }
  $('#btnAdd').onclick=()=> openPatientForm(); $('#btnCancel').onclick=()=> $('#patientDialog').close(); $('#btnReload').onclick=loadPatients; $('#btnClear').onclick=()=>{ $('#search').value=''; PSTATE.query=''; renderPatients(); }; $('#search').oninput=e=>{ PSTATE.query=e.target.value; renderPatients(); };
  $('#patientForm').onsubmit=async (ev)=>{ ev.preventDefault(); const id=$('#p_id').value || ('p_'+Date.now().toString(36)); const payload={ action:'upsert_patient', data:{ id, nombre:$('#p_full_name').value.trim(), documento:$('#p_document_id').value.trim(), telefono:$('#p_phone').value.trim(), email:$('#p_email').value.trim(), fecha_nacimiento:$('#p_birthdate').value||'', direccion:$('#p_address').value.trim(), notas:$('#p_notes').value.trim() } }; if(!payload.data.nombre){ alert('El nombre es obligatorio.'); return;} try{ showNet('Guardando...'); await apiPost(payload); $('#patientDialog').close(); await loadPatients(); showNet('Guardado ✓'); setTimeout(()=>showNet(''),1500);}catch(e){ alert('Error guardando: '+e.message); showNet('Error'); } };
  async function deletePatient(id){ const p=PSTATE.patients.find(x=> x.id===id); if(!p) return; if(!confirm(`¿Eliminar a "${p.nombre}"?`)) return; try{ showNet('Eliminando...'); await apiPost({action:'delete_patient', data:{id}}); await loadPatients(); showNet('Eliminado ✓'); setTimeout(()=>showNet(''),1500);}catch(e){ alert('Error: '+e.message); showNet('Error'); } }
  async function openPatientDetail(id){ const p=PSTATE.patients.find(x=> x.id===id); if(!p) return; const d=$('#detail'); d.classList.remove('hidden'); d.innerHTML=`<div class="bg-white rounded-2xl shadow p-6 mb-4"><div class="flex items-start justify-between"><div><h2 class="text-2xl font-bold">${p.nombre}</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2 text-sm"><div><span class="text-gray-500">Documento:</span> ${p.documento||'—'}</div><div><span class="text-gray-500">Teléfono:</span> ${p.telefono||'—'}</div><div><span class="text-gray-500">Email:</span> ${p.email||'—'}</div><div><span class="text-gray-500">Fecha nac.:</span> ${humanDate(p.fecha_nacimiento)}</div><div class="md:col-span-2"><span class="text-gray-500">Dirección:</span> ${p.direccion||'—'}</div><div class="md:col-span-2"><span class="text-gray-500">Notas:</span> ${p.notas||'—'}</div></div></div><div class="space-x-2"><button class="px-3 py-2 rounded-xl bg-amber-500 text-white hover:bg-amber-600" id="editPatient">Editar</button></div></div></div>`; $('#editPatient').onclick=()=> openPatientForm(p.id); window.scrollTo({top:0,behavior:'smooth'}); }
  loadPatients();

  /* ====== INVENTARIO (localStorage con categorías, docs multi-ítems, historial y CPP) ====== */
  const LS_INV='inv_products_v3'; const LS_CATS='inv_categories_v1'; const LS_DOCS='inv_documents_v2'; const LS_HIST='inv_history_v1';
  const money=n=> Number(n||0).toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}); const today=()=> new Date().toISOString().slice(0,10);
  let INV=JSON.parse(localStorage.getItem(LS_INV)||'[]'); let CATS=JSON.parse(localStorage.getItem(LS_CATS)||'[]'); let DOCS=JSON.parse(localStorage.getItem(LS_DOCS)||'[]'); let HIST=JSON.parse(localStorage.getItem(LS_HIST)||'[]');
  const saveINV=()=> localStorage.setItem(LS_INV, JSON.stringify(INV)); const saveCATS=()=> localStorage.setItem(LS_CATS, JSON.stringify(CATS)); const saveDOCS=()=> localStorage.setItem(LS_DOCS, JSON.stringify(DOCS)); const saveHIST=()=> localStorage.setItem(LS_HIST, JSON.stringify(HIST));

  // UI comunes
  const invSearch=$('#invSearch'), invCatFilter=$('#invCatFilter'), invList=$('#invList');
  function refreshCatFilter(){ const chosen=invCatFilter.value||''; invCatFilter.innerHTML='<option value="">Todas las categorías</option>'+ CATS.map(c=>`<option ${c===chosen?'selected':''}>${c}</option>`).join(''); }
  function fillCatSelect(){ const sel=$('#prod_cat'); sel.innerHTML=CATS.map(c=>`<option value="${c}">${c}</option>`).join(''); }
  function invSummary(){ $('#cardSku').textContent=INV.length; const totalUnits=INV.reduce((a,p)=> a+Number(p.stock||0),0); const totalCost=INV.reduce((a,p)=> a+(Number(p.stock||0)*Number(p.avg_cost||0)),0); $('#cardUnits').textContent=totalUnits.toLocaleString('es-CO'); $('#cardCost').textContent=money(totalCost); }
  function renderInv(){ refreshCatFilter(); invSummary(); const q=(invSearch.value||'').toLowerCase(); const cat=invCatFilter.value||''; const rows=INV.filter(p=>{ const txt=(p.name+' '+(p.cat||'')).toLowerCase(); return (!q||txt.includes(q)) && (!cat||p.cat===cat); }).sort((a,b)=> a.name.localeCompare(b.name)); invList.innerHTML=rows.length?'':'<div class="text-gray-500">No hay productos.</div>'; for(const p of rows){ const div=document.createElement('div'); div.className='border rounded-2xl p-4 flex items-center justify-between'; div.innerHTML=`<div><div class="font-semibold">${p.name} ${p.cat?`<span class="chip">${p.cat}</span>`:''}</div><div class="text-sm text-gray-500">Stock: <b>${p.stock||0}</b> · Costo prom.: <b>${money(p.avg_cost||0)}</b></div></div><div class="flex gap-2"><button class="px-3 py-2 rounded-xl bg-indigo-600 text-white hover:bg-indigo-700" data-hist="${p.id}">Historial</button><button class="px-3 py-2 rounded-xl bg-amber-500 text-white hover:bg-amber-600" data-edit="${p.id}">Editar</button><button class="px-3 py-2 rounded-xl bg-red-600 text-white hover:bg-red-700" data-del="${p.id}">Eliminar</button></div>`; invList.appendChild(div);} invList.querySelectorAll('[data-edit]').forEach(b=> b.onclick=()=> openProdForm(b.dataset.edit)); invList.querySelectorAll('[data-del]').forEach(b=> b.onclick=()=> deleteProd(b.dataset.del)); invList.querySelectorAll('[data-hist]').forEach(b=> b.onclick=()=> openHist(b.dataset.hist)); }

  // Producto CRUD
  function openProdForm(id){ const dlg=$('#invProdDialog'), f=$('#invProdForm'); f.reset(); fillCatSelect(); $('#prod_id').value=id||''; const p=INV.find(x=> x.id===id); if(p){ $('#prod_name').value=p.name; $('#prod_cat').value=p.cat||''; } dlg.showModal(); }
  $('#btnAddProduct').onclick=()=> openProdForm(); $('#btnInvProdCancel').onclick=()=> $('#invProdDialog').close();
  $('#invProdForm').onsubmit=(e)=>{ e.preventDefault(); const id=$('#prod_id').value||('sku_'+Date.now().toString(36)); const name=$('#prod_name').value.trim(); const cat=$('#prod_cat').value; if(!name||!cat){ alert('Nombre y categoría son obligatorios'); return;} const i=INV.findIndex(x=> x.id===id); if(i>=0){ INV[i].name=name; INV[i].cat=cat; } else { INV.push({id,name,cat,stock:0,avg_cost:0,created_at:new Date().toISOString()}); } saveINV(); $('#invProdDialog').close(); renderInv(); };
  function deleteProd(id){ const p=INV.find(x=> x.id===id); if(!p) return; if(!confirm(`¿Eliminar "${p.name}"? Esto no borra su historial ni documentos.`)) return; INV=INV.filter(x=> x.id!==id); saveINV(); renderInv(); }

  // Categorías CRUD
  function openCats(){ const dlg=$('#catDialog'); renderCats(); dlg.showModal(); }
  function renderCats(){ const list=$('#catList'); list.innerHTML=CATS.length?'':'<div class="text-gray-500">Sin categorías.</div>'; for(const c of CATS){ const row=document.createElement('div'); row.className='border rounded-2xl p-3 flex items-center justify-between'; row.innerHTML=`<div>${c}</div><div class="flex gap-2"><button class="px-3 py-1 rounded-xl bg-amber-500 text-white hover:bg-amber-600" data-rename="${c}">Renombrar</button><button class="px-3 py-1 rounded-xl bg-red-600 text-white hover:bg-red-700" data-del="${c}">Eliminar</button></div>`; list.appendChild(row);} list.querySelectorAll('[data-del]').forEach(b=> b.onclick=()=>{ const c=b.dataset.del; if(INV.some(p=> p.cat===c)){ alert('No puedes eliminar una categoría en uso.'); return;} CATS=CATS.filter(x=> x!==c); saveCATS(); renderCats(); renderInv(); }); list.querySelectorAll('[data-rename]').forEach(b=> b.onclick=()=>{ const old=b.dataset.rename; const neo=prompt('Nuevo nombre para la categoría', old); if(!neo) return; if(CATS.includes(neo)){ alert('Ya existe esa categoría'); return;} CATS=CATS.map(x=> x===old? neo:x); INV=INV.map(p=> p.cat===old? {...p,cat:neo}:p); saveCATS(); saveINV(); renderCats(); renderInv(); }); }
  $('#btnCats').onclick=openCats; $('#btnCatClose').onclick=()=> $('#catDialog').close(); $('#catForm').onsubmit=(e)=>{ e.preventDefault(); const name=$('#catName').value.trim(); if(!name){ alert('Escribe un nombre'); return;} if(CATS.includes(name)){ alert('Ya existe'); return;} CATS.push(name); saveCATS(); $('#catName').value=''; renderCats(); renderInv(); };

  // Documentos (multi-ítems)
  function nextDocNo(type){ const base=type==='compra'?'C':'V'; const count=DOCS.filter(d=> d.type===type).length+1; return base+String(count).padStart(5,'0'); }
  let MOVE_MODE='in'; let LINES=[]; // {id,product_id,qty,unit_cost}
  function openMoveForm(mode){ MOVE_MODE=mode; LINES=[]; const dlg=$('#invMoveDialog'); const f=$('#invMoveForm'); f.reset(); $('#invMoveTitle').textContent=(mode==='in'?'Compra':'Venta'); $('#doc_type').value=(mode==='in'?'compra':'venta'); $('#doc_no').value=nextDocNo(mode==='in'?'compra':'venta'); $('#doc_date').value=today(); $('#thCost').style.display=(mode==='in')?'table-cell':'none'; renderLines(); dlg.showModal(); }
  $('#btnIn').onclick=()=> openMoveForm('in'); $('#btnOut').onclick=()=> openMoveForm('out'); $('#btnInvMoveCancel').onclick=()=> $('#invMoveDialog').close();

  function addLine(){ if(!INV.length){ alert('Primero crea productos.'); return;} const id='ln_'+Date.now().toString(36)+Math.random().toString(36).slice(2,5); const first=INV[0]?.id||''; LINES.push({id,product_id:first,qty:1,unit_cost:0}); renderLines(); }
  function removeLine(id){ LINES=LINES.filter(l=> l.id!==id); renderLines(); }
  function setLineValue(id,field,value){ const i=LINES.findIndex(l=> l.id===id); if(i>=0){ LINES[i][field]=value; renderTotal(); } }
  function renderLines(){ const body=$('#linesBody'); body.innerHTML=''; for(const ln of LINES){ const prodOpts=INV.map(p=> `<option value="${p.id}" ${ln.product_id===p.id?'selected':''}>${p.name}</option>`).join(''); const costCell = (MOVE_MODE==='in')? `<input type="number" min="0" step="0.01" class="px-2 py-1 rounded border w-full" value="${ln.unit_cost}" data-field="unit_cost" data-id="${ln.id}">` : `<span class="text-gray-400">—</span>`; const p=INV.find(x=> x.id===ln.product_id); const unit = (MOVE_MODE==='in')? (Number(ln.unit_cost||0)) : Number(p?.avg_cost||0); const subtotal = Number(ln.qty||0)*Number(unit||0); const tr=document.createElement('tr'); tr.innerHTML=`<td><select class="px-2 py-1 rounded border w-full" data-field="product_id" data-id="${ln.id}">${prodOpts}</select></td><td><input type="number" min="1" step="1" class="px-2 py-1 rounded border w-full" value="${ln.qty}" data-field="qty" data-id="${ln.id}"></td><td>${costCell}</td><td>${money(subtotal)}</td><td><button type="button" class="px-2 py-1 rounded bg-red-600 text-white" data-del="${ln.id}">Quitar</button></td>`; body.appendChild(tr);} body.querySelectorAll('select, input').forEach(el=> el.onchange=(e)=>{ const id=e.target.dataset.id; const field=e.target.dataset.field; const val=(field==='qty')? Number(e.target.value||0) : (field==='unit_cost'? Number(e.target.value||0) : e.target.value); setLineValue(id,field,val); renderLines(); }); body.querySelectorAll('[data-del]').forEach(b=> b.onclick=()=> removeLine(b.dataset.del)); renderTotal(); }
  function renderTotal(){ let total=0; for(const ln of LINES){ const p=INV.find(x=> x.id===ln.product_id); const unit=(MOVE_MODE==='in')? Number(ln.unit_cost||0) : Number(p?.avg_cost||0); total += Number(ln.qty||0) * unit; } $('#docTotal').textContent=money(total); }
  $('#btnAddLine').onclick=addLine; // primer ítem por defecto al abrir

  $('#invMoveForm').onsubmit=(e)=>{ e.preventDefault(); const type=(MOVE_MODE==='in'?'compra':'venta'); if(!LINES.length){ alert('Agrega al menos un ítem.'); return;} if(LINES.some(l=> !l.product_id || !l.qty || l.qty<=0 || (type==='compra' && (!l.unit_cost || l.unit_cost<=0)))){ alert('Verifica cantidades y costos.'); return;} const header={ id:'doc_'+Date.now().toString(36), type, number:$('#doc_no').value, date:$('#doc_date').value, party:$('#doc_party').value.trim(), notes:$('#doc_notes').value.trim(), total:0, lines: JSON.parse(JSON.stringify(LINES)) };
    // aplicar movimientos línea por línea
    let docTotal=0; for(const ln of header.lines){ const p=INV.find(x=> x.id===ln.product_id); if(!p){ alert('Producto no encontrado'); return;} const stock_before=Number(p.stock||0), avg_before=Number(p.avg_cost||0); if(type==='compra'){ const unit=Number(ln.unit_cost||0); const newQty=stock_before + Number(ln.qty||0); const newAvg = newQty>0 ? ((stock_before*avg_before + Number(ln.qty||0)*unit) / newQty) : unit; p.stock=newQty; p.avg_cost=newAvg; docTotal += Number(ln.qty||0)*unit; HIST.push({ id:'h_'+Date.now().toString(36)+Math.random().toString(36).slice(2,5), product_id:p.id, date:header.date, type, doc_no:header.number, qty:Number(ln.qty||0), unit_cost:unit, avg_before, avg_after:newAvg, stock_before, stock_after:newQty, party:header.party, notes:header.notes }); }
      else { // venta
        const unit=avg_before; if(Number(ln.qty||0) > stock_before){ alert(`Stock insuficiente para ${p.name}`); return;} const newQty = stock_before - Number(ln.qty||0); p.stock=newQty; // avg se mantiene
        docTotal += Number(ln.qty||0)*unit; HIST.push({ id:'h_'+Date.now().toString(36)+Math.random().toString(36).slice(2,5), product_id:p.id, date:header.date, type, doc_no:header.number, qty:Number(ln.qty||0), unit_cost:unit, avg_before, avg_after:avg_before, stock_before, stock_after:newQty, party:header.party, notes:header.notes }); }
    }
    header.total = docTotal; DOCS.push(header); saveDOCS(); saveHIST(); saveINV(); $('#invMoveDialog').close(); renderInv(); };

  // Historial por producto
  function openHist(prod_id){ const p=INV.find(x=> x.id===prod_id); const dlg=$('#historyDialog'); $('#histProdName').textContent=p? p.name : ''; const rows=HIST.filter(h=> h.product_id===prod_id).sort((a,b)=> String(b.date||'').localeCompare(String(a.date||''))); const list=$('#histList'); const meta=$('#histMeta'); meta.textContent=`Stock: ${p?.stock||0} · Costo prom.: ${money(p?.avg_cost||0)}`; list.innerHTML=rows.length?'':'<div class="text-gray-500">Sin movimientos.</div>'; for(const h of rows){ const el=document.createElement('div'); el.className='border rounded-2xl p-3 flex items-center justify-between'; el.innerHTML=`<div><div class="font-semibold">${h.type==='compra'?'🟢 Compra':'🔴 Venta'} — ${h.doc_no} · ${h.date}</div><div class="text-sm text-gray-500">Cant: ${h.qty} · Costo unit.: ${money(h.unit_cost||0)} · Promedio: ${money(h.avg_before||0)} → <b>${money(h.avg_after||0)}</b> · Stock: ${h.stock_before} → <b>${h.stock_after}</b></div>${h.party? `<div class='text-sm'>${h.party}</div>`:''}${h.notes? `<div class='text-sm'>${h.notes}</div>`:''}</div>`; list.appendChild(el);} dlg.showModal(); }
  $('#btnHistClose').onclick=()=> $('#historyDialog').close();

  // Documentos: listado general
  function openDocs(){ const dlg=$('#docsDialog'); const list=$('#docsList'); const rows=DOCS.slice().sort((a,b)=> String(b.date||'').localeCompare(String(a.date||''))); list.innerHTML=rows.length?'':'<div class="text-gray-500">Sin documentos.</div>'; for(const d of rows){ const items = d.lines.map(ln=>{ const p=INV.find(x=> x.id===ln.product_id); const unit = (d.type==='compra')? Number(ln.unit_cost||0) : Number((INV.find(x=> x.id===ln.product_id)?.avg_cost_at_doc)||0); return `${p?p.name:'(producto)'} × ${ln.qty}${d.type==='compra'? ' @ '+money(ln.unit_cost): ''}`; }).join(' · '); const el=document.createElement('div'); el.className='border rounded-2xl p-3'; el.innerHTML=`<div class="flex items-center justify-between"><div><div class="font-semibold">${d.type==='compra'?'🟢 Compra':'🔴 Venta'} — ${d.number} · ${d.date}</div><div class="text-sm text-gray-500">${items}</div>${d.party? `<div class='text-sm'>${d.party}</div>`:''}${d.notes? `<div class='text-sm'>${d.notes}</div>`:''}</div><div class="font-bold">${money(d.total)}</div></div>`; list.appendChild(el);} dlg.showModal(); }
  $('#btnDocs').onclick=openDocs; $('#btnDocsClose').onclick=()=> $('#docsDialog').close();

  // Filtros inventario
  $('#invSearch').oninput=renderInv; $('#invCatFilter').onchange=renderInv; renderInv();

  /* ====== INGRESOS/GASTOS (sin cambios) ====== */
  const LS_CF='cashflow_v1'; let CF=JSON.parse(localStorage.getItem(LS_CF)||'[]'); const saveCF=()=> localStorage.setItem(LS_CF, JSON.stringify(CF)); const cfList=$('#cfList'); const cfHuman=n=> Number(n||0).toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}); function renderCF(){ const q=($('#cfSearch').value||'').toLowerCase(), t=$('#cfType').value||''; const f=$('#cfFrom').value? new Date($('#cfFrom').value):null; const to=$('#cfTo').value? new Date($('#cfTo').value):null; const rows=CF.filter(r=>{ const txt=`${r.concept||''} ${r.category||''} ${r.method||''}`.toLowerCase(); const okQ=!q||txt.includes(q); const okT=!t||r.type===t; const d=r.date? new Date(r.date+'T00:00:00'):null; const okF=!f||(d&&d>=f); const okTo=!to||(d&&d<=to); return okQ&&okT&&okF&&okTo; }).sort((a,b)=> String(b.date||'').localeCompare(String(a.date||''))); cfList.innerHTML=rows.length?'':'<div class="text-gray-500">Sin movimientos.</div>'; for(const r of rows){ const card=document.createElement('div'); card.className='border rounded-2xl p-4 flex items-center justify-between'; card.innerHTML=`<div><div class="font-semibold">${r.type==='ingreso'?'🟢 Ingreso':'🔴 Gasto'} — ${r.concept||'(sin concepto)'} <span class="text-gray-500">· ${r.category||'—'}</span></div><div class="text-sm text-gray-500">${r.date||'—'} · ${r.method||'—'}</div>${r.notes? `<div class="text-sm mt-1">${r.notes}</div>`:''}</div><div class="flex items-center gap-2"><div class="font-bold ${r.type==='ingreso'?'text-emerald-700':'text-red-700'}">${cfHuman(r.amount)}</div><button class="px-3 py-2 rounded-xl bg-amber-500 text-white hover:bg-amber-600" data-edit="${r.id}">Editar</button><button class="px-3 py-2 rounded-xl bg-red-600 text-white hover:bg-red-700" data-del="${r.id}">Eliminar</button></div>`; cfList.appendChild(card);} cfList.querySelectorAll('[data-edit]').forEach(b=> b.onclick=()=> openCfForm(b.dataset.edit)); cfList.querySelectorAll('[data-del]').forEach(b=> b.onclick=()=> deleteCF(b.dataset.del)); const tin=rows.filter(r=> r.type==='ingreso').reduce((a,r)=> a+Number(r.amount||0),0); const tout=rows.filter(r=> r.type==='gasto').reduce((a,r)=> a+Number(r.amount||0),0); $('#cfIncome').textContent=cfHuman(tin); $('#cfExpense').textContent=cfHuman(tout); const bal=tin-tout; const el=$('#cfBalance'); el.textContent=cfHuman(bal); el.className='text-2xl font-bold ' + (bal>=0?'text-emerald-700':'text-red-700'); }
  function openCfForm(id){ const dlg=$('#cfDialog'); const f=$('#cfForm'); f.reset(); $('#cfDialogTitle').textContent=id?'Editar movimiento':'Nuevo movimiento'; $('#cf_id').value=id||''; $('#cf_date').value=today(); if(id){ const r=CF.find(x=> x.id===id); if(r){ $('#cf_date').value=r.date||''; $('#cf_type').value=r.type||'ingreso'; $('#cf_category').value=r.category||''; $('#cf_amount').value=r.amount||''; $('#cf_concept').value=r.concept||''; $('#cf_method').value=r.method||''; $('#cf_notes').value=r.notes||''; } } dlg.showModal(); }
  function deleteCF(id){ const r=CF.find(x=> x.id===id); if(!r) return; if(!confirm(`¿Eliminar "${r.type} · ${r.concept}"?`)) return; CF=CF.filter(x=> x.id!==id); saveCF(); renderCF(); }
  $('#btnCfAdd').onclick=()=> openCfForm(); $('#btnCfCancel').onclick=()=> $('#cfDialog').close(); $('#cfForm').onsubmit=(e)=>{ e.preventDefault(); const id=$('#cf_id').value||('tx_'+Date.now().toString(36)); const r={ id, date:$('#cf_date').value, type:$('#cf_type').value, category:$('#cf_category').value.trim(), amount:Number($('#cf_amount').value||0), concept:$('#cf_concept').value.trim(), method:$('#cf_method').value.trim(), notes:$('#cf_notes').value.trim() }; if(!r.date||!r.type||!r.category||!r.concept||!r.amount){ alert('Completa fecha, tipo, categoría, concepto y monto.'); return;} const i=CF.findIndex(x=> x.id===id); if(i>=0) CF[i]=r; else CF.push(r); saveCF(); $('#cfDialog').close(); renderCF(); };
  $('#cfSearch').oninput=renderCF; $('#cfType').onchange=renderCF; $('#cfFrom').onchange=renderCF; $('#cfTo').onchange=renderCF; $('#btnCfClear').onclick=()=>{ $('#cfSearch').value=''; $('#cfType').value=''; $('#cfFrom').value=''; $('#cfTo').value=''; renderCF(); }; renderCF();

  /* ====== TABS ====== */
  const tabPatients=$('#tabPatients'), tabInventory=$('#tabInventory'), tabCashflow=$('#tabCashflow'); function setTab(t){ show($('#patientsView'), t==='patients'); show($('#inventoryView'), t==='inventory'); show($('#cashflowView'), t==='cashflow'); tabPatients.classList.toggle('tab-active', t==='patients'); tabInventory.classList.toggle('tab-active', t==='inventory'); tabCashflow.classList.toggle('tab-active', t==='cashflow'); }
  tabPatients.onclick=()=> setTab('patients'); tabInventory.onclick=()=> setTab('inventory'); tabCashflow.onclick=()=> setTab('cashflow');
  </script>